eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
  oauth2:
    audience: api://default
    issuer: https://dev-23720267.okta.com/oauth2/default
    client-secret: ${OKTA_SECRET}
    client-id: ${OKTA_CLIENT_ID}
